imports:
    - { resource: "local/" }
    - { resource: "workflows.yaml" }

pimcore:
    bundles:
        search_paths:
            - bundles/RestApiBundle
    email:
        sender:
            name: "Pimcore Mail sender"
            email: siwachs128@gmail.com
        return:
            name: "Pimcore Mail receiver"
            email: "siwachs128@gmail.com"

twig:
    paths: ["%kernel.project_dir%/bundles/RestApiBundle/Resources/views"]

services:
    _defaults:
        autowire: true, # Auto inject dependency in services
        autoconfigure: true # Auto registers your services as commands, event subscribers, etc.

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

#### TRANSLATIONS
#    translations:
#        case_insensitive: true

#### SYMFONY OVERRIDES
framework:
    mailer:
        transports:
            main: smtp://siwachs128@gmail.com:gmvdqrwidshqkcad@smtp.gmail.com:587
