parameters:
    secret: azluFrhehN8EkmiAbue8JdbDc9s+GF+PTdIhc4ycKqI=
    pimcore_asset_path: "/public/var/assets"
    notification_sender: "siwachs128@gmail.com"
    notification_receiver: "siwachs128@gmail.com"
    notification_subject: "Pimcore Data Importer"
    notification_message: "Data object have been imported."
    notification_template_path: "/importerMail"

    available_groups:
        "Gaming and Entertainment": 3
        "Photography Enthusiasts": 4
        "Budget Conscious Users": 5
        "Business Productivity": 1

    group_attributes:
        "Gaming and Entertainment":
            "Processor Performance": 8
            "Display Quality": 21
            "Entertainment Apps": 11
            "Store Description": 20
        "Photography Enthusiasts":
            "Camera Specs": 12
            "Photography Modes": 13
            "Image Stabilization": 14
            "Editing Software Compatibility": 15
            "Store Description": 20
        "Budget Conscious Users":
            "Value for Money": 16
            "Performance": 17
            "Essential Features": 18
            "Affordability": 19
            "Store Description": 20
        "Business Productivity":
            "Store Description": 20
            "Productivity Apps": 5
            "Multitasking Capabilities": 6
            "Work Software Compatibility": 7

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\:
        resource: "../src/Controller"
        public: true
        tags: ["controller.service_arguments"]

    Pimcore\Mail:
        class: Pimcore\Mail

    calculate_price:
        class: App\Controller\ActualPriceCalculator

    # Twig Ext
    App\Twig\Extension\UniqidExtension:
        tags: ["twig.extension"]

    # Event Listeners
    App\EventListener\ObjectListener:
        tags:
            - {
                  name: kernel.event_listener,
                  event: pimcore.dataobject.preUpdate,
                  method: onObjectPreUpdate,
              }
            - {
                  name: kernel.event_listener,
                  event: pimcore.dataobject.postUpdate,
                  method: onObjectPostUpdate,
              }

    # Workflow Listeners
    App\EventListener\WorkflowListener:
        tags:
            - {
                  name: kernel.event_listener,
                  event: workflow.product_workflow.transition.start_enrichment,
                  method: onTransitionToEnrichment,
              }
            - {
                  name: kernel.event_listener,
                  event: workflow.product_workflow.transition.finish_enrichment,
                  method: onTransitionToTechnicalities,
              }
